---

- hosts: all
  become: yes
  serial: "50%"
  vars:
    change_id: CH0000721
  pre_tasks:
  - include: roles/pre-post-task/pre-task.yaml
  roles:
  - firewalld
  post_tasks:
  - include: roles/pre-post-task/post-task.yaml
